### ISSUE TITLE
not working in my firefox 45.0.1

### ISSUE THREAD

**Issue by aliramw** [coolwanglu/hypnotic#2]
error message:

too much recursion
  Array: function(dummy) {

TypeError: Array.prototype.slice is undefined
  ...=function(a){return function(b){return T(Array.prototype.slice.call(arguments,1)...

TypeError: b.trigger is not a function
  ...nt(t,"mousemove",b.throttle(function(){b.trigger("window.mousemove")},250,50),!1...

**Comment by coolwanglu** [comment]
It seems that 

``` js
Array: function(dummy) {
  Array.apply(...)
}
```

The inner `Array` will refer to the outer `Array`, instead of the globally one.
Maybe I should change the interpreter.
